version: '3'

services:
  api:
    build: .
    volumes:
    - app:/go/src/app
    ports:
      - "8080:8080"
    networks:
      - backend
    restart: always

networks:
  backend:

volumes:
  app:

